services:
  app:
    build: .
    ports:
      - "8080:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ""
      DB_NAME: atelier_devops
      DB_PORT: 3306
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: atelier_devops 